services:
  - type: web
    name: catsgotogedog
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
