import type { ReviewData, SearchCardData } from "@/types/types";

export const placeDetailDummy = {
  title: "도그밀리 DOGMILY",
  thumbnail: "/assets/samples/placeThumbnail_sample.png",
  isVisited: false,
  likedCount: 63,
  viewCount: 63,
  isLiked: false,
  lat: 37.8171378819,
  lng: 127.5276443195,
  tags: ["가족과 함께", "힐링", "즐거운"],
  desc: "도그밀리에는 반려견과 보호자가 함께 편안한 시간을 보낼 수 있는 감성 펫카페입니다. 고급스러운 인테리어와 청결한 환경 속에서, 반려견은 자유롭게 뛰놀고 보호자는 여유로운 커피 타임을 즐길 수 있어요. 강아지를 위한 수제 간식과 보호자를 위한 음료/디저트 메뉴도 준비되어 있어, 모두가 행복한 공간을 지향합니다.",
  address: "서울시 노원구 노원로 37길",
  number: "134-4567",
  reviewCount: 10,
};

export const testReviewPhotos = [
  "/assets/samples/review_sample/1.jpg",
  "/assets/samples/review_sample/2.jpg",
  "/assets/samples/review_sample/3.jpg",
  "/assets/samples/review_sample/4.jpg",
  "/assets/samples/review_sample/5.jpg",
  "/assets/samples/review_sample/6.jpg",
  "/assets/samples/review_sample/7.jpg",
  "/assets/samples/review_sample/6.jpg",
  "/assets/samples/review_sample/5.jpg",
  "/assets/samples/review_sample/4.jpg",
  "/assets/samples/review_sample/3.jpg",
];

export const testReviews: ReviewData[] = [
  {
    id: "review-1",
    profileImg: "/assets/samples/profile_sample.png",
    name: "해피댕댕이",
    date: new Date("2024-05-10"),
    rating: 4.5,
    content:
      "강아지랑 같이 다녀온 최고의 장소였어요! 사람도 친절하고 애견을 위한 시설이 잘 갖춰져 있어서 마음 놓고 다녀올 수 있었습니다. 특히 야외 테라스에서의 뷰가 인상 깊었어요.",
    heartCount: 12,
    isLiked: true,
    thumbnail: "/assets/samples/review_sample/3.jpg",
  },
  {
    id: "review-2",
    profileImg: "/assets/samples/profile_sample.png",
    name: "냥덕",
    date: new Date("2024-06-21"),
    rating: 5,
    content: "고양이도 마음껏 뛰어놀 수 있는 넓은 공간! 만족합니다.",
    heartCount: 8,
    isLiked: false,
    thumbnail: "/assets/samples/review_sample/5.jpg",
  },
  {
    id: "review-3",
    profileImg: "/assets/samples/profile_sample.png",
    name: "박산책",
    date: new Date("2024-04-30"),
    rating: 4,
    content: "산책 코스가 예쁘고 깨끗해요. 강아지가 무척 좋아했어요.",
    heartCount: 5,
    isLiked: false,
    thumbnail: "/assets/samples/review_sample/1.jpg",
  },
  {
    id: "review-4",
    profileImg: "/assets/samples/profile_sample.png",
    name: "루루맘",
    date: new Date("2024-07-01"),
    rating: 4.5,
    content:
      "전반적으로 좋아요! 단, 사람이 조금 많은 시간대는 피하는 걸 추천해요. 주차장도 협소한 편이에요.",
    heartCount: 10,
    isLiked: true,
    thumbnail: "/assets/samples/review_sample/7.jpg",
  },
  {
    id: "review-5",
    profileImg: "/assets/samples/profile_sample.png",
    name: "우디",
    date: new Date("2024-03-18"),
    rating: 3.5,
    content: "시설은 괜찮지만 애완동물을 위한 배려는 조금 부족한 느낌이었어요.",
    heartCount: 3,
    isLiked: false,
    thumbnail: "/assets/samples/review_sample/2.jpg",
  },
  {
    id: "review-6",
    profileImg: "/assets/samples/profile_sample.png",
    name: "슬기로운반려생활",
    date: new Date("2024-06-03"),
    rating: 5,
    content:
      "정말 최고의 경험이었어요! 강아지와 함께한 여행 중 가장 기억에 남는 장소입니다. 숙소도 깨끗했고, 주변 식당도 반려동물 동반 가능해서 편했어요. 다시 가고 싶어요!",
    heartCount: 18,
    isLiked: true,
    thumbnail: "/assets/samples/review_sample/6.jpg",
  },
  {
    id: "review-7",
    profileImg: "/assets/samples/profile_sample.png",
    name: "냥냥펀치",
    date: new Date("2024-05-26"),
    rating: 4,
    content: "고양이가 좋아했는지는 모르겠지만 저는 만족합니다ㅋㅋ",
    heartCount: 6,
    isLiked: false,
    thumbnail: "/assets/samples/review_sample/4.jpg",
  },
  {
    id: "review-8",
    profileImg: "/assets/samples/profile_sample.png",
    name: "산책홀릭",
    date: new Date("2024-07-10"),
    rating: 4.5,
    content:
      "반려동물과 함께할 수 있는 산책로 중 탑급! 벤치나 그늘이 많아서 여름에도 괜찮았어요.",
    heartCount: 9,
    isLiked: false,
    thumbnail: "/assets/samples/review_sample/1.jpg",
  },
  {
    id: "review-9",
    profileImg: "/assets/samples/profile_sample.png",
    name: "멍이집사",
    date: new Date("2024-05-04"),
    rating: 3,
    content:
      "기대보다 좀 아쉬웠어요. 애견 동반 가능은 했지만 눈치가 좀 보였네요.",
    heartCount: 2,
    isLiked: false,
    thumbnail: "/assets/samples/review_sample/5.jpg",
  },
  {
    id: "review-10",
    profileImg: "/assets/samples/profile_sample.png",
    name: "강쥐사랑",
    date: new Date("2024-07-18"),
    rating: 5,
    content:
      "완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. 완벽합니다! 이 가격에 이 정도 퀄리티라니. 추천드려요. ",
    heartCount: 14,
    isLiked: true,
    thumbnail: "/assets/samples/review_sample/7.jpg",
  },
];

export const testSearchData: SearchCardData[] = [
  {
    id: "place-1",
    title: "카페 무지개",
    address: "서울 강남구",
    closeDay: "매주 월요일",
    mapX: 127.0276,
    mapY: 37.4979,
    rating: 4.235,
    tags: ["반려동물 동반", "야외석", "조용한 분위기"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: false,
    createdAt: new Date("2024-07-01"),
    heartCount: 20,
  },
  {
    id: "place-2",
    title: "멍냥파크",
    address: "경기 성남시",
    closeDay: "매주 화요일",
    mapX: 127.1267,
    mapY: 37.4103,
    rating: 4.752,
    tags: ["놀이터", "반려견 전용", "넓은 공간"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: true,
    createdAt: new Date("2024-07-05"),
    heartCount: 32,
  },
  {
    id: "place-3",
    title: "냥이숲",
    address: "부산 해운대구",
    closeDay: "명절 당일",
    mapX: 129.158,
    mapY: 35.1632,
    rating: 3.942,
    tags: ["캣타워", "포토존", "실내"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: false,
    createdAt: new Date("2024-06-25"),
    heartCount: 15,
  },
  {
    id: "place-4",
    title: "댕댕이 마켓",
    address: "서울 마포구",
    closeDay: "추석 당일",
    mapX: 126.9011,
    mapY: 37.5563,
    rating: 4.621,
    tags: ["용품 쇼핑", "먹거리", "체험"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: true,
    createdAt: new Date("2024-07-10"),
    heartCount: 45,
  },
  {
    id: "place-5",
    title: "동물원길",
    address: "대구 수성구",
    closeDay: "매주 수요일",
    mapX: 128.6284,
    mapY: 35.8562,
    rating: 3.385,
    tags: ["산책로", "자연", "반려견 동반"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: false,
    createdAt: new Date("2024-06-28"),
    heartCount: 12,
  },
  {
    id: "place-6",
    title: "펫힐링센터",
    address: "인천 연수구",
    closeDay: "매주 금요일",
    mapX: 126.6728,
    mapY: 37.4089,
    rating: 4.128,
    tags: ["마사지", "반려동물 스파", "건강관리"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: true,
    createdAt: new Date("2024-07-08"),
    heartCount: 30,
  },
  {
    id: "place-7",
    title: "댕냥카페",
    address: "광주 북구",
    closeDay: "매주 목요일",
    mapX: 126.9119,
    mapY: 35.1741,
    rating: 4.512,
    tags: ["강아지", "고양이", "디저트"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: true,
    createdAt: new Date("2024-07-04"),
    heartCount: 27,
  },
  {
    id: "place-8",
    title: "펫테마파크",
    address: "제주 제주시",
    closeDay: "없음",
    mapX: 126.5312,
    mapY: 33.4996,
    rating: 3.758,
    tags: ["테마파크", "놀이시설", "반려동물"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: false,
    createdAt: new Date("2024-06-30"),
    heartCount: 18,
  },
  {
    id: "place-9",
    title: "고양이책방",
    address: "서울 종로구",
    closeDay: "매주 일요일",
    mapX: 126.9849,
    mapY: 37.5729,
    rating: 4.847,
    tags: ["북카페", "조용한 공간", "고양이"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: true,
    createdAt: new Date("2024-07-09"),
    heartCount: 40,
  },
  {
    id: "place-10",
    title: "펫시네마",
    address: "경기 고양시",
    closeDay: "명절 당일",
    mapX: 126.8327,
    mapY: 37.6584,
    rating: 4.002,
    tags: ["영화관", "실내", "반려동물 동반"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: false,
    createdAt: new Date("2024-07-02"),
    heartCount: 22,
  },
  {
    id: "place-11",
    title: "댕댕마트",
    address: "경기 안양시",
    closeDay: "매주 월요일",
    mapX: 126.9769,
    mapY: 37.3943,
    rating: 4.093,
    tags: ["반려동물 식품", "대형매장", "셀프목욕"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: false,
    createdAt: new Date("2024-07-03"),
    heartCount: 16,
  },
  {
    id: "place-12",
    title: "산책쉼터",
    address: "강원 춘천시",
    closeDay: "없음",
    mapX: 127.7308,
    mapY: 37.8813,
    rating: 3.562,
    tags: ["휴식 공간", "자연", "반려동물 산책"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: false,
    createdAt: new Date("2024-06-26"),
    heartCount: 9,
  },
  {
    id: "place-13",
    title: "멍냥운동장",
    address: "울산 중구",
    closeDay: "매주 수요일",
    mapX: 129.3114,
    mapY: 35.5662,
    rating: 4.673,
    tags: ["운동장", "놀이공간", "애견훈련"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: true,
    createdAt: new Date("2024-07-06"),
    heartCount: 33,
  },
  {
    id: "place-14",
    title: "댕냥하우스",
    address: "서울 용산구",
    closeDay: "매주 금요일",
    mapX: 126.9644,
    mapY: 37.5326,
    rating: 4.319,
    tags: ["호텔", "위탁", "프리미엄"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: true,
    createdAt: new Date("2024-07-07"),
    heartCount: 36,
  },
  {
    id: "place-15",
    title: "냥냥미술관",
    address: "전북 전주시",
    closeDay: "월요일",
    mapX: 127.148,
    mapY: 35.8242,
    rating: 3.814,
    tags: ["고양이", "예술", "전시"],
    img: "/assets/samples/resultcard_sample.jpg",
    isLiked: false,
    createdAt: new Date("2024-06-29"),
    heartCount: 11,
  },
];
